Dont ignore subnets from command line args if provided
openshift/moactl pull request #190
Opened 2020-11-25 11:16 UTC by nimrodshn

JIRA: https://issues.redhat.com/browse/SDA-3367

cc: @igoihman  @vkareh

2020-11-25 12:38 UTC, vkareh commented
/ok-to-test

2020-11-25 13:24 UTC, vkareh requested changes
This needs a few changes in addition to my comments. The `GetMultipleOptions` element does not support defaults, so it's not populated from the command-line. One way of doing that:
```diff
diff --git a/pkg/interactive/interactive.go b/pkg/interactive/interactive.go
index b273e75..af65f2f 100644
--- a/pkg/interactive/interactive.go
+++ b/pkg/interactive/interactive.go
@@ -110,12 +110,12 @@ func parseInt(str string) (num int, err error) {
 func GetMultipleOptions(input Input) ([]string, error) {
        var err error
        res := make([]string, 0)
-       dflt, ok := input.Default.(string)
+       dflt, ok := input.Default.([]string)
        if !ok {
-               dflt = ""
+               dflt = []string{}
        }
        question := input.Question
-       if !input.Required && dflt == "" {
+       if !input.Required && len(dflt) == 0 {
                question = fmt.Sprintf("%s (optional)", question)
        }
        prompt := &survey.MultiSelect{
```
and the corresponding usage:
```diff
diff --git a/cmd/create/cluster/cmd.go b/cmd/create/cluster/cmd.go
index c117544..58d5d7f 100644
--- a/cmd/create/cluster/cmd.go
+++ b/cmd/create/cluster/cmd.go
@@ -417,12 +416,18 @@ func run(cmd *cobra.Command, _ []string) {
                mapSubnetToAZ := make(map[string]string)
                mapAZCreated := make(map[string]bool)
                options := make([]string, len(subnets))
+               optionDefaults := make([]string, len(subnetIDs))
                for i, subnet := range subnets {
                        subnetID := awssdk.StringValue(subnet.SubnetId)
                        availabilityZone := awssdk.StringValue(subnet.AvailabilityZone)
 
                        // Create the options to prompt the user.
                        options[i] = setSubnetOption(subnetID, availabilityZone)
+                       for _, subnetArg := range subnetIDs {
+                               if subnetArg == subnetID {
+                                       optionDefaults = append(optionDefaults, setSubnetOption(subnetID, availabilityZone))
+                               }
+                       }
                        mapSubnetToAZ[subnetID] = availabilityZone
                        mapAZCreated[availabilityZone] = false
                }
@@ -432,6 +437,7 @@ func run(cmd *cobra.Command, _ []string) {
                                Help:     cmd.Flags().Lookup("subnet-ids").Usage,
                                Required: false,
                                Options:  options,
+                               Default:  optionDefaults,
                        })
                        if err != nil {
                                reporter.Errorf("Expected valid subnet IDs: %s", err)
```
This means that the options passed in the command line are now pre-selected.

2020-11-25 13:24 UTC, vkareh commented on cmd/create/cluster/cmd.go
> +			"Subnets are comma separated, for example: --subnet-ids='subnet-1','subnet-2'."+
Remove the single quotes, they should not be necessary once you fix the `Default` used for pre-populating the `GetMultipleOptions` element: `--subnet-ids=subnet-1,subnet-2`:
```
$ rosa create cluster -i --dry-run --subnet-ids=subnet-050b5a070768d2737,subnet-074572b18f5698f1f
I: Interactive mode enabled.
Any optional fields can be left empty and a default will be selected.
? Cluster name: foo
? Multiple availability zones (optional): No
? AWS region: us-east-1
? OpenShift version (optional): 
? Subnet IDs:  [Use arrows to move, space to select, <right> to all, <left> to none, type to filter, ? for more help]
> [x]  subnet-050b5a070768d2737 (us-east-1f)
  [x]  subnet-074572b18f5698f1f (us-east-1a)
  [ ]  subnet-09a60d10e113314e5 (us-east-1a)
  [ ]  subnet-011158850f4d15a53 (us-east-1a)
  [ ]  subnet-0ba3f0ead1f486510 (us-east-1a)
  [ ]  subnet-0c031ef9162b35f04 (us-east-1a)
  [ ]  subnet-0c7b531f9375931b1 (us-east-1f)
```

2020-11-26 07:40 UTC, nimrodshn commented on cmd/create/cluster/cmd.go
>  	if interactive.Enabled() {
But this reverts the "defaults" changes you suggested above - I think it makes sense though.

2020-11-26 09:39 UTC, nimrodshn commented
@vkareh Done. ptal

2020-11-26 14:22 UTC, vkareh commented
/lgtm

2020-11-26 14:24 UTC, merged